### ISSUE TITLE
Proszę powiedzieć co to robi?

### ISSUE THREAD

**Issue by mowczare** [FreexD/spcaa#3]
Eng: Please tell me what it does?

**Comment by FreexD** [comment]
It implements a multifrontal solver for solving big matrices in O(n). For the algorithm to work, the matrix have to be both diagonally-dense and sparse otherwise as it only takes into account the elements located around it's diagonal. The solver can bo used to calculate good approximations of certain numeric problems (like Heat-Transfer od Advection) in both **implicit** and **explicit** manner.

**Comment by mowczare** [comment]
Does it however provide a specific transformation from an implicit to explicit manner? And how would you rate a performance of this algorithm from 'not performant' to 'really fast like a speed demon'?

**Comment by FreexD** [comment]
The transformation can be done in no time using my head only. No notes required. The implementation however does not provide any explicit way for those kinds of transformations, which makes my head the supreme being for that specific case. With the scale provided the performance can only be described by 'really fast like a speed demon'.

**Comment by mowczare** [comment]
Thank you Gaben, that satisfied my curiosity.
